### PR TITLE
fixed the prompt message

### PR DESCRIPTION
**Pull request by Charlie195**
I fixed the prompt message issue.

### CODE REVIEW

**Comment by Ming713** [comment]
Hi Charlie, well done! but I found other issues, please check it again.
image

**Review by Ming713 — COMMENTED** [review]
Please check the prompt issue I found and highlighted with a red rectangle in the comment.

**Comment by Charlie195** [comment]
> Hi Charlie, well done! but I found other issues, please check it again.

Good capture! I will fix it in next issue.

**Comment by Ming713** [comment]
> > Hi Charlie, well done! but I found other issues, please check it again.
> 
> Good capture! I will fix it in next issue.

Got it and approved it.

**Review by Ming713 — APPROVED** [review]
LGTM!

**Pull request merged**
